### ISSUE TITLE
Inserting unwanted data if VOL does not present into API (COMP: Computer Age Management Services)

### ISSUE THREAD

**Issue by iamkrishnagawade** [iamkrishnagawade/25dmpd#11]
`npm run start-scraper CAM`

TypeError: Cannot read property 'VOL' of null
    at feachPrice (/home/synerzip/Data/MML/25dmpd/scraper/runner.js:63:32)
    at process._tickCallback (internal/process/next_tick.js:68:7)
^CCaught interrupt signal
Caught interrupt signal
Caught interrupt signal

**Comment by iamkrishnagawade** [comment]
Fixed in defect Not able to add watchlist using ID AB16 (axisbank) from scraper #1
