### ISSUE TITLE
Bug:  [ERROR] TypeError: Cannot destructure property 'pricecurrent' of 'obj.data.data' as it is null.

### ISSUE THREAD

**Issue by iamkrishnagawade** [iamkrishnagawade/25dmpd#43]
[25/6/2021 9:55:59] [ERROR] TypeError: Cannot destructure property 'pricecurrent' of 'obj.data.data' as it is null.
    at E:\Data\Github\25dmpd\util\cpPrice.util.js:42:17
    at Array.map (<anonymous>)
    at E:\Data\Github\25dmpd\util\cpPrice.util.js:40:21
    at wrap (E:\Data\Github\25dmpd\node_modules\axios\lib\helpers\spread.js:25:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async exports.getPriceFeeds (E:\Data\Github\25dmpd\util\cpPrice.util.js:35:12)
    at async Timeout._onTimeout (E:\Data\Github\25dmpd\services\spyPriceFeeds.service.js:10:24)

**Comment by iamkrishnagawade** [comment]
Fixed
